<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.0
 */

/**
 * Database `spendllyadmin_api`
 */

/* `spendllyadmin_api`.`countries` */
$countries = array(
  array('iso' => 'AF','name' => 'AFGHANISTAN','nicename' => 'Afghanistan','iso3' => 'AFG'),
  array('iso' => 'AL','name' => 'ALBANIA','nicename' => 'Albania','iso3' => 'ALB'),
  array('iso' => 'DZ','name' => 'ALGERIA','nicename' => 'Algeria','iso3' => 'DZA'),
  array('iso' => 'AS','name' => 'AMERICAN SAMOA','nicename' => 'American Samoa','iso3' => 'ASM'),
  array('iso' => 'AD','name' => 'ANDORRA','nicename' => 'Andorra','iso3' => 'AND'),
  array('iso' => 'AO','name' => 'ANGOLA','nicename' => 'Angola','iso3' => 'AGO'),
  array('iso' => 'AI','name' => 'ANGUILLA','nicename' => 'Anguilla','iso3' => 'AIA'),
  array('iso' => 'AQ','name' => 'ANTARCTICA','nicename' => 'Antarctica','iso3' => NULL),
  array('iso' => 'AG','name' => 'ANTIGUA AND BARBUDA','nicename' => 'Antigua and Barbuda','iso3' => 'ATG'),
  array('iso' => 'AR','name' => 'ARGENTINA','nicename' => 'Argentina','iso3' => 'ARG'),
  array('iso' => 'AM','name' => 'ARMENIA','nicename' => 'Armenia','iso3' => 'ARM'),
  array('iso' => 'AW','name' => 'ARUBA','nicename' => 'Aruba','iso3' => 'ABW'),
  array('iso' => 'AU','name' => 'AUSTRALIA','nicename' => 'Australia','iso3' => 'AUS'),
  array('iso' => 'AT','name' => 'AUSTRIA','nicename' => 'Austria','iso3' => 'AUT'),
  array('iso' => 'AZ','name' => 'AZERBAIJAN','nicename' => 'Azerbaijan','iso3' => 'AZE'),
  array('iso' => 'BS','name' => 'BAHAMAS','nicename' => 'Bahamas','iso3' => 'BHS'),
  array('iso' => 'BH','name' => 'BAHRAIN','nicename' => 'Bahrain','iso3' => 'BHR'),
  array('iso' => 'BD','name' => 'BANGLADESH','nicename' => 'Bangladesh','iso3' => 'BGD'),
  array('iso' => 'BB','name' => 'BARBADOS','nicename' => 'Barbados','iso3' => 'BRB'),
  array('iso' => 'BY','name' => 'BELARUS','nicename' => 'Belarus','iso3' => 'BLR'),
  array('iso' => 'BE','name' => 'BELGIUM','nicename' => 'Belgium','iso3' => 'BEL'),
  array('iso' => 'BZ','name' => 'BELIZE','nicename' => 'Belize','iso3' => 'BLZ'),
  array('iso' => 'BJ','name' => 'BENIN','nicename' => 'Benin','iso3' => 'BEN'),
  array('iso' => 'BM','name' => 'BERMUDA','nicename' => 'Bermuda','iso3' => 'BMU'),
  array('iso' => 'BT','name' => 'BHUTAN','nicename' => 'Bhutan','iso3' => 'BTN'),
  array('iso' => 'BO','name' => 'BOLIVIA','nicename' => 'Bolivia','iso3' => 'BOL'),
  array('iso' => 'BA','name' => 'BOSNIA AND HERZEGOVINA','nicename' => 'Bosnia and Herzegovina','iso3' => 'BIH'),
  array('iso' => 'BW','name' => 'BOTSWANA','nicename' => 'Botswana','iso3' => 'BWA'),
  array('iso' => 'BV','name' => 'BOUVET ISLAND','nicename' => 'Bouvet Island','iso3' => NULL),
  array('iso' => 'BR','name' => 'BRAZIL','nicename' => 'Brazil','iso3' => 'BRA'),
  array('iso' => 'IO','name' => 'BRITISH INDIAN OCEAN TERRITORY','nicename' => 'British Indian Ocean Territory','iso3' => NULL),
  array('iso' => 'BN','name' => 'BRUNEI DARUSSALAM','nicename' => 'Brunei Darussalam','iso3' => 'BRN'),
  array('iso' => 'BG','name' => 'BULGARIA','nicename' => 'Bulgaria','iso3' => 'BGR'),
  array('iso' => 'BF','name' => 'BURKINA FASO','nicename' => 'Burkina Faso','iso3' => 'BFA'),
  array('iso' => 'BI','name' => 'BURUNDI','nicename' => 'Burundi','iso3' => 'BDI'),
  array('iso' => 'KH','name' => 'CAMBODIA','nicename' => 'Cambodia','iso3' => 'KHM'),
  array('iso' => 'CM','name' => 'CAMEROON','nicename' => 'Cameroon','iso3' => 'CMR'),
  array('iso' => 'CA','name' => 'CANADA','nicename' => 'Canada','iso3' => 'CAN'),
  array('iso' => 'CV','name' => 'CAPE VERDE','nicename' => 'Cape Verde','iso3' => 'CPV'),
  array('iso' => 'KY','name' => 'CAYMAN ISLANDS','nicename' => 'Cayman Islands','iso3' => 'CYM'),
  array('iso' => 'CF','name' => 'CENTRAL AFRICAN REPUBLIC','nicename' => 'Central African Republic','iso3' => 'CAF'),
  array('iso' => 'TD','name' => 'CHAD','nicename' => 'Chad','iso3' => 'TCD'),
  array('iso' => 'CL','name' => 'CHILE','nicename' => 'Chile','iso3' => 'CHL'),
  array('iso' => 'CN','name' => 'CHINA','nicename' => 'China','iso3' => 'CHN'),
  array('iso' => 'CX','name' => 'CHRISTMAS ISLAND','nicename' => 'Christmas Island','iso3' => NULL),
  array('iso' => 'CC','name' => 'COCOS (KEELING) ISLANDS','nicename' => 'Cocos (Keeling) Islands','iso3' => NULL),
  array('iso' => 'CO','name' => 'COLOMBIA','nicename' => 'Colombia','iso3' => 'COL'),
  array('iso' => 'KM','name' => 'COMOROS','nicename' => 'Comoros','iso3' => 'COM'),
  array('iso' => 'CG','name' => 'CONGO','nicename' => 'Congo','iso3' => 'COG'),
  array('iso' => 'CD','name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','nicename' => 'Congo, the Democratic Republic of the','iso3' => 'COD'),
  array('iso' => 'CK','name' => 'COOK ISLANDS','nicename' => 'Cook Islands','iso3' => 'COK'),
  array('iso' => 'CR','name' => 'COSTA RICA','nicename' => 'Costa Rica','iso3' => 'CRI'),
  array('iso' => 'CI','name' => 'COTE D\'IVOIRE','nicename' => 'Cote D\'Ivoire','iso3' => 'CIV'),
  array('iso' => 'HR','name' => 'CROATIA','nicename' => 'Croatia','iso3' => 'HRV'),
  array('iso' => 'CU','name' => 'CUBA','nicename' => 'Cuba','iso3' => 'CUB'),
  array('iso' => 'CY','name' => 'CYPRUS','nicename' => 'Cyprus','iso3' => 'CYP'),
  array('iso' => 'CZ','name' => 'CZECH REPUBLIC','nicename' => 'Czech Republic','iso3' => 'CZE'),
  array('iso' => 'DK','name' => 'DENMARK','nicename' => 'Denmark','iso3' => 'DNK'),
  array('iso' => 'DJ','name' => 'DJIBOUTI','nicename' => 'Djibouti','iso3' => 'DJI'),
  array('iso' => 'DM','name' => 'DOMINICA','nicename' => 'Dominica','iso3' => 'DMA'),
  array('iso' => 'DO','name' => 'DOMINICAN REPUBLIC','nicename' => 'Dominican Republic','iso3' => 'DOM'),
  array('iso' => 'EC','name' => 'ECUADOR','nicename' => 'Ecuador','iso3' => 'ECU'),
  array('iso' => 'EG','name' => 'EGYPT','nicename' => 'Egypt','iso3' => 'EGY'),
  array('iso' => 'SV','name' => 'EL SALVADOR','nicename' => 'El Salvador','iso3' => 'SLV'),
  array('iso' => 'GQ','name' => 'EQUATORIAL GUINEA','nicename' => 'Equatorial Guinea','iso3' => 'GNQ'),
  array('iso' => 'ER','name' => 'ERITREA','nicename' => 'Eritrea','iso3' => 'ERI'),
  array('iso' => 'EE','name' => 'ESTONIA','nicename' => 'Estonia','iso3' => 'EST'),
  array('iso' => 'ET','name' => 'ETHIOPIA','nicename' => 'Ethiopia','iso3' => 'ETH'),
  array('iso' => 'FK','name' => 'FALKLAND ISLANDS (MALVINAS)','nicename' => 'Falkland Islands (Malvinas)','iso3' => 'FLK'),
  array('iso' => 'FO','name' => 'FAROE ISLANDS','nicename' => 'Faroe Islands','iso3' => 'FRO'),
  array('iso' => 'FJ','name' => 'FIJI','nicename' => 'Fiji','iso3' => 'FJI'),
  array('iso' => 'FI','name' => 'FINLAND','nicename' => 'Finland','iso3' => 'FIN'),
  array('iso' => 'FR','name' => 'FRANCE','nicename' => 'France','iso3' => 'FRA'),
  array('iso' => 'GF','name' => 'FRENCH GUIANA','nicename' => 'French Guiana','iso3' => 'GUF'),
  array('iso' => 'PF','name' => 'FRENCH POLYNESIA','nicename' => 'French Polynesia','iso3' => 'PYF'),
  array('iso' => 'TF','name' => 'FRENCH SOUTHERN TERRITORIES','nicename' => 'French Southern Territories','iso3' => NULL),
  array('iso' => 'GA','name' => 'GABON','nicename' => 'Gabon','iso3' => 'GAB'),
  array('iso' => 'GM','name' => 'GAMBIA','nicename' => 'Gambia','iso3' => 'GMB'),
  array('iso' => 'GE','name' => 'GEORGIA','nicename' => 'Georgia','iso3' => 'GEO'),
  array('iso' => 'DE','name' => 'GERMANY','nicename' => 'Germany','iso3' => 'DEU'),
  array('iso' => 'GH','name' => 'GHANA','nicename' => 'Ghana','iso3' => 'GHA'),
  array('iso' => 'GI','name' => 'GIBRALTAR','nicename' => 'Gibraltar','iso3' => 'GIB'),
  array('iso' => 'GR','name' => 'GREECE','nicename' => 'Greece','iso3' => 'GRC'),
  array('iso' => 'GL','name' => 'GREENLAND','nicename' => 'Greenland','iso3' => 'GRL'),
  array('iso' => 'GD','name' => 'GRENADA','nicename' => 'Grenada','iso3' => 'GRD'),
  array('iso' => 'GP','name' => 'GUADELOUPE','nicename' => 'Guadeloupe','iso3' => 'GLP'),
  array('iso' => 'GU','name' => 'GUAM','nicename' => 'Guam','iso3' => 'GUM'),
  array('iso' => 'GT','name' => 'GUATEMALA','nicename' => 'Guatemala','iso3' => 'GTM'),
  array('iso' => 'GN','name' => 'GUINEA','nicename' => 'Guinea','iso3' => 'GIN'),
  array('iso' => 'GW','name' => 'GUINEA-BISSAU','nicename' => 'Guinea-Bissau','iso3' => 'GNB'),
  array('iso' => 'GY','name' => 'GUYANA','nicename' => 'Guyana','iso3' => 'GUY'),
  array('iso' => 'HT','name' => 'HAITI','nicename' => 'Haiti','iso3' => 'HTI'),
  array('iso' => 'HM','name' => 'HEARD ISLAND AND MCDONALD ISLANDS','nicename' => 'Heard Island and Mcdonald Islands','iso3' => NULL),
  array('iso' => 'VA','name' => 'HOLY SEE (VATICAN CITY STATE)','nicename' => 'Holy See (Vatican City State)','iso3' => 'VAT'),
  array('iso' => 'HN','name' => 'HONDURAS','nicename' => 'Honduras','iso3' => 'HND'),
  array('iso' => 'HK','name' => 'HONG KONG','nicename' => 'Hong Kong','iso3' => 'HKG'),
  array('iso' => 'HU','name' => 'HUNGARY','nicename' => 'Hungary','iso3' => 'HUN'),
  array('iso' => 'IS','name' => 'ICELAND','nicename' => 'Iceland','iso3' => 'ISL'),
  array('iso' => 'IN','name' => 'INDIA','nicename' => 'India','iso3' => 'IND'),
  array('iso' => 'ID','name' => 'INDONESIA','nicename' => 'Indonesia','iso3' => 'IDN'),
  array('iso' => 'IR','name' => 'IRAN, ISLAMIC REPUBLIC OF','nicename' => 'Iran, Islamic Republic of','iso3' => 'IRN'),
  array('iso' => 'IQ','name' => 'IRAQ','nicename' => 'Iraq','iso3' => 'IRQ'),
  array('iso' => 'IE','name' => 'IRELAND','nicename' => 'Ireland','iso3' => 'IRL'),
  array('iso' => 'IL','name' => 'ISRAEL','nicename' => 'Israel','iso3' => 'ISR'),
  array('iso' => 'IT','name' => 'ITALY','nicename' => 'Italy','iso3' => 'ITA'),
  array('iso' => 'JM','name' => 'JAMAICA','nicename' => 'Jamaica','iso3' => 'JAM'),
  array('iso' => 'JP','name' => 'JAPAN','nicename' => 'Japan','iso3' => 'JPN'),
  array('iso' => 'JO','name' => 'JORDAN','nicename' => 'Jordan','iso3' => 'JOR'),
  array('iso' => 'KZ','name' => 'KAZAKHSTAN','nicename' => 'Kazakhstan','iso3' => 'KAZ'),
  array('iso' => 'KE','name' => 'KENYA','nicename' => 'Kenya','iso3' => 'KEN'),
  array('iso' => 'KI','name' => 'KIRIBATI','nicename' => 'Kiribati','iso3' => 'KIR'),
  array('iso' => 'KP','name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','nicename' => 'Korea, Democratic People\'s Republic of','iso3' => 'PRK'),
  array('iso' => 'KR','name' => 'KOREA, REPUBLIC OF','nicename' => 'Korea, Republic of','iso3' => 'KOR'),
  array('iso' => 'KW','name' => 'KUWAIT','nicename' => 'Kuwait','iso3' => 'KWT'),
  array('iso' => 'KG','name' => 'KYRGYZSTAN','nicename' => 'Kyrgyzstan','iso3' => 'KGZ'),
  array('iso' => 'LA','name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC','nicename' => 'Lao People\'s Democratic Republic','iso3' => 'LAO'),
  array('iso' => 'LV','name' => 'LATVIA','nicename' => 'Latvia','iso3' => 'LVA'),
  array('iso' => 'LB','name' => 'LEBANON','nicename' => 'Lebanon','iso3' => 'LBN'),
  array('iso' => 'LS','name' => 'LESOTHO','nicename' => 'Lesotho','iso3' => 'LSO'),
  array('iso' => 'LR','name' => 'LIBERIA','nicename' => 'Liberia','iso3' => 'LBR'),
  array('iso' => 'LY','name' => 'LIBYAN ARAB JAMAHIRIYA','nicename' => 'Libyan Arab Jamahiriya','iso3' => 'LBY'),
  array('iso' => 'LI','name' => 'LIECHTENSTEIN','nicename' => 'Liechtenstein','iso3' => 'LIE'),
  array('iso' => 'LT','name' => 'LITHUANIA','nicename' => 'Lithuania','iso3' => 'LTU'),
  array('iso' => 'LU','name' => 'LUXEMBOURG','nicename' => 'Luxembourg','iso3' => 'LUX'),
  array('iso' => 'MO','name' => 'MACAO','nicename' => 'Macao','iso3' => 'MAC'),
  array('iso' => 'MK','name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','nicename' => 'Macedonia, the Former Yugoslav Republic of','iso3' => 'MKD'),
  array('iso' => 'MG','name' => 'MADAGASCAR','nicename' => 'Madagascar','iso3' => 'MDG'),
  array('iso' => 'MW','name' => 'MALAWI','nicename' => 'Malawi','iso3' => 'MWI'),
  array('iso' => 'MY','name' => 'MALAYSIA','nicename' => 'Malaysia','iso3' => 'MYS'),
  array('iso' => 'MV','name' => 'MALDIVES','nicename' => 'Maldives','iso3' => 'MDV'),
  array('iso' => 'ML','name' => 'MALI','nicename' => 'Mali','iso3' => 'MLI'),
  array('iso' => 'MT','name' => 'MALTA','nicename' => 'Malta','iso3' => 'MLT'),
  array('iso' => 'MH','name' => 'MARSHALL ISLANDS','nicename' => 'Marshall Islands','iso3' => 'MHL'),
  array('iso' => 'MQ','name' => 'MARTINIQUE','nicename' => 'Martinique','iso3' => 'MTQ'),
  array('iso' => 'MR','name' => 'MAURITANIA','nicename' => 'Mauritania','iso3' => 'MRT'),
  array('iso' => 'MU','name' => 'MAURITIUS','nicename' => 'Mauritius','iso3' => 'MUS'),
  array('iso' => 'YT','name' => 'MAYOTTE','nicename' => 'Mayotte','iso3' => NULL),
  array('iso' => 'MX','name' => 'MEXICO','nicename' => 'Mexico','iso3' => 'MEX'),
  array('iso' => 'FM','name' => 'MICRONESIA, FEDERATED STATES OF','nicename' => 'Micronesia, Federated States of','iso3' => 'FSM'),
  array('iso' => 'MD','name' => 'MOLDOVA, REPUBLIC OF','nicename' => 'Moldova, Republic of','iso3' => 'MDA'),
  array('iso' => 'MC','name' => 'MONACO','nicename' => 'Monaco','iso3' => 'MCO'),
  array('iso' => 'MN','name' => 'MONGOLIA','nicename' => 'Mongolia','iso3' => 'MNG'),
  array('iso' => 'MS','name' => 'MONTSERRAT','nicename' => 'Montserrat','iso3' => 'MSR'),
  array('iso' => 'MA','name' => 'MOROCCO','nicename' => 'Morocco','iso3' => 'MAR'),
  array('iso' => 'MZ','name' => 'MOZAMBIQUE','nicename' => 'Mozambique','iso3' => 'MOZ'),
  array('iso' => 'MM','name' => 'MYANMAR','nicename' => 'Myanmar','iso3' => 'MMR'),
  array('iso' => 'NA','name' => 'NAMIBIA','nicename' => 'Namibia','iso3' => 'NAM'),
  array('iso' => 'NR','name' => 'NAURU','nicename' => 'Nauru','iso3' => 'NRU'),
  array('iso' => 'NP','name' => 'NEPAL','nicename' => 'Nepal','iso3' => 'NPL'),
  array('iso' => 'NL','name' => 'NETHERLANDS','nicename' => 'Netherlands','iso3' => 'NLD'),
  array('iso' => 'AN','name' => 'NETHERLANDS ANTILLES','nicename' => 'Netherlands Antilles','iso3' => 'ANT'),
  array('iso' => 'NC','name' => 'NEW CALEDONIA','nicename' => 'New Caledonia','iso3' => 'NCL'),
  array('iso' => 'NZ','name' => 'NEW ZEALAND','nicename' => 'New Zealand','iso3' => 'NZL'),
  array('iso' => 'NI','name' => 'NICARAGUA','nicename' => 'Nicaragua','iso3' => 'NIC'),
  array('iso' => 'NE','name' => 'NIGER','nicename' => 'Niger','iso3' => 'NER'),
  array('iso' => 'NG','name' => 'NIGERIA','nicename' => 'Nigeria','iso3' => 'NGA'),
  array('iso' => 'NU','name' => 'NIUE','nicename' => 'Niue','iso3' => 'NIU'),
  array('iso' => 'NF','name' => 'NORFOLK ISLAND','nicename' => 'Norfolk Island','iso3' => 'NFK'),
  array('iso' => 'MP','name' => 'NORTHERN MARIANA ISLANDS','nicename' => 'Northern Mariana Islands','iso3' => 'MNP'),
  array('iso' => 'NO','name' => 'NORWAY','nicename' => 'Norway','iso3' => 'NOR'),
  array('iso' => 'OM','name' => 'OMAN','nicename' => 'Oman','iso3' => 'OMN'),
  array('iso' => 'PK','name' => 'PAKISTAN','nicename' => 'Pakistan','iso3' => 'PAK'),
  array('iso' => 'PW','name' => 'PALAU','nicename' => 'Palau','iso3' => 'PLW'),
  array('iso' => 'PS','name' => 'PALESTINIAN TERRITORY, OCCUPIED','nicename' => 'Palestinian Territory, Occupied','iso3' => NULL),
  array('iso' => 'PA','name' => 'PANAMA','nicename' => 'Panama','iso3' => 'PAN'),
  array('iso' => 'PG','name' => 'PAPUA NEW GUINEA','nicename' => 'Papua New Guinea','iso3' => 'PNG'),
  array('iso' => 'PY','name' => 'PARAGUAY','nicename' => 'Paraguay','iso3' => 'PRY'),
  array('iso' => 'PE','name' => 'PERU','nicename' => 'Peru','iso3' => 'PER'),
  array('iso' => 'PH','name' => 'PHILIPPINES','nicename' => 'Philippines','iso3' => 'PHL'),
  array('iso' => 'PN','name' => 'PITCAIRN','nicename' => 'Pitcairn','iso3' => 'PCN'),
  array('iso' => 'PL','name' => 'POLAND','nicename' => 'Poland','iso3' => 'POL'),
  array('iso' => 'PT','name' => 'PORTUGAL','nicename' => 'Portugal','iso3' => 'PRT'),
  array('iso' => 'PR','name' => 'PUERTO RICO','nicename' => 'Puerto Rico','iso3' => 'PRI'),
  array('iso' => 'QA','name' => 'QATAR','nicename' => 'Qatar','iso3' => 'QAT'),
  array('iso' => 'RE','name' => 'REUNION','nicename' => 'Reunion','iso3' => 'REU'),
  array('iso' => 'RO','name' => 'ROMANIA','nicename' => 'Romania','iso3' => 'ROM'),
  array('iso' => 'RU','name' => 'RUSSIAN FEDERATION','nicename' => 'Russian Federation','iso3' => 'RUS'),
  array('iso' => 'RW','name' => 'RWANDA','nicename' => 'Rwanda','iso3' => 'RWA'),
  array('iso' => 'SH','name' => 'SAINT HELENA','nicename' => 'Saint Helena','iso3' => 'SHN'),
  array('iso' => 'KN','name' => 'SAINT KITTS AND NEVIS','nicename' => 'Saint Kitts and Nevis','iso3' => 'KNA'),
  array('iso' => 'LC','name' => 'SAINT LUCIA','nicename' => 'Saint Lucia','iso3' => 'LCA'),
  array('iso' => 'PM','name' => 'SAINT PIERRE AND MIQUELON','nicename' => 'Saint Pierre and Miquelon','iso3' => 'SPM'),
  array('iso' => 'VC','name' => 'SAINT VINCENT AND THE GRENADINES','nicename' => 'Saint Vincent and the Grenadines','iso3' => 'VCT'),
  array('iso' => 'WS','name' => 'SAMOA','nicename' => 'Samoa','iso3' => 'WSM'),
  array('iso' => 'SM','name' => 'SAN MARINO','nicename' => 'San Marino','iso3' => 'SMR'),
  array('iso' => 'ST','name' => 'SAO TOME AND PRINCIPE','nicename' => 'Sao Tome and Principe','iso3' => 'STP'),
  array('iso' => 'SA','name' => 'SAUDI ARABIA','nicename' => 'Saudi Arabia','iso3' => 'SAU'),
  array('iso' => 'SN','name' => 'SENEGAL','nicename' => 'Senegal','iso3' => 'SEN'),
  array('iso' => 'CS','name' => 'SERBIA AND MONTENEGRO','nicename' => 'Serbia and Montenegro','iso3' => NULL),
  array('iso' => 'SC','name' => 'SEYCHELLES','nicename' => 'Seychelles','iso3' => 'SYC'),
  array('iso' => 'SL','name' => 'SIERRA LEONE','nicename' => 'Sierra Leone','iso3' => 'SLE'),
  array('iso' => 'SG','name' => 'SINGAPORE','nicename' => 'Singapore','iso3' => 'SGP'),
  array('iso' => 'SK','name' => 'SLOVAKIA','nicename' => 'Slovakia','iso3' => 'SVK'),
  array('iso' => 'SI','name' => 'SLOVENIA','nicename' => 'Slovenia','iso3' => 'SVN'),
  array('iso' => 'SB','name' => 'SOLOMON ISLANDS','nicename' => 'Solomon Islands','iso3' => 'SLB'),
  array('iso' => 'SO','name' => 'SOMALIA','nicename' => 'Somalia','iso3' => 'SOM'),
  array('iso' => 'ZA','name' => 'SOUTH AFRICA','nicename' => 'South Africa','iso3' => 'ZAF'),
  array('iso' => 'GS','name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','nicename' => 'South Georgia and the South Sandwich Islands','iso3' => NULL),
  array('iso' => 'ES','name' => 'SPAIN','nicename' => 'Spain','iso3' => 'ESP'),
  array('iso' => 'LK','name' => 'SRI LANKA','nicename' => 'Sri Lanka','iso3' => 'LKA'),
  array('iso' => 'SD','name' => 'SUDAN','nicename' => 'Sudan','iso3' => 'SDN'),
  array('iso' => 'SR','name' => 'SURINAME','nicename' => 'Suriname','iso3' => 'SUR'),
  array('iso' => 'SJ','name' => 'SVALBARD AND JAN MAYEN','nicename' => 'Svalbard and Jan Mayen','iso3' => 'SJM'),
  array('iso' => 'SZ','name' => 'SWAZILAND','nicename' => 'Swaziland','iso3' => 'SWZ'),
  array('iso' => 'SE','name' => 'SWEDEN','nicename' => 'Sweden','iso3' => 'SWE'),
  array('iso' => 'CH','name' => 'SWITZERLAND','nicename' => 'Switzerland','iso3' => 'CHE'),
  array('iso' => 'SY','name' => 'SYRIAN ARAB REPUBLIC','nicename' => 'Syrian Arab Republic','iso3' => 'SYR'),
  array('iso' => 'TW','name' => 'TAIWAN, PROVINCE OF CHINA','nicename' => 'Taiwan, Province of China','iso3' => 'TWN'),
  array('iso' => 'TJ','name' => 'TAJIKISTAN','nicename' => 'Tajikistan','iso3' => 'TJK'),
  array('iso' => 'TZ','name' => 'TANZANIA, UNITED REPUBLIC OF','nicename' => 'Tanzania, United Republic of','iso3' => 'TZA'),
  array('iso' => 'TH','name' => 'THAILAND','nicename' => 'Thailand','iso3' => 'THA'),
  array('iso' => 'TL','name' => 'TIMOR-LESTE','nicename' => 'Timor-Leste','iso3' => NULL),
  array('iso' => 'TG','name' => 'TOGO','nicename' => 'Togo','iso3' => 'TGO'),
  array('iso' => 'TK','name' => 'TOKELAU','nicename' => 'Tokelau','iso3' => 'TKL'),
  array('iso' => 'TO','name' => 'TONGA','nicename' => 'Tonga','iso3' => 'TON'),
  array('iso' => 'TT','name' => 'TRINIDAD AND TOBAGO','nicename' => 'Trinidad and Tobago','iso3' => 'TTO'),
  array('iso' => 'TN','name' => 'TUNISIA','nicename' => 'Tunisia','iso3' => 'TUN'),
  array('iso' => 'TR','name' => 'TURKEY','nicename' => 'Turkey','iso3' => 'TUR'),
  array('iso' => 'TM','name' => 'TURKMENISTAN','nicename' => 'Turkmenistan','iso3' => 'TKM'),
  array('iso' => 'TC','name' => 'TURKS AND CAICOS ISLANDS','nicename' => 'Turks and Caicos Islands','iso3' => 'TCA'),
  array('iso' => 'TV','name' => 'TUVALU','nicename' => 'Tuvalu','iso3' => 'TUV'),
  array('iso' => 'UG','name' => 'UGANDA','nicename' => 'Uganda','iso3' => 'UGA'),
  array('iso' => 'UA','name' => 'UKRAINE','nicename' => 'Ukraine','iso3' => 'UKR'),
  array('iso' => 'AE','name' => 'UNITED ARAB EMIRATES','nicename' => 'United Arab Emirates','iso3' => 'ARE'),
  array('iso' => 'GB','name' => 'UNITED KINGDOM','nicename' => 'United Kingdom','iso3' => 'GBR'),
  array('iso' => 'US','name' => 'UNITED STATES','nicename' => 'United States','iso3' => 'USA'),
  array('iso' => 'UM','name' => 'UNITED STATES MINOR OUTLYING ISLANDS','nicename' => 'United States Minor Outlying Islands','iso3' => NULL),
  array('iso' => 'UY','name' => 'URUGUAY','nicename' => 'Uruguay','iso3' => 'URY'),
  array('iso' => 'UZ','name' => 'UZBEKISTAN','nicename' => 'Uzbekistan','iso3' => 'UZB'),
  array('iso' => 'VU','name' => 'VANUATU','nicename' => 'Vanuatu','iso3' => 'VUT'),
  array('iso' => 'VE','name' => 'VENEZUELA','nicename' => 'Venezuela','iso3' => 'VEN'),
  array('iso' => 'VN','name' => 'VIET NAM','nicename' => 'Viet Nam','iso3' => 'VNM'),
  array('iso' => 'VG','name' => 'VIRGIN ISLANDS, BRITISH','nicename' => 'Virgin Islands, British','iso3' => 'VGB'),
  array('iso' => 'VI','name' => 'VIRGIN ISLANDS, U.S.','nicename' => 'Virgin Islands, U.s.','iso3' => 'VIR'),
  array('iso' => 'WF','name' => 'WALLIS AND FUTUNA','nicename' => 'Wallis and Futuna','iso3' => 'WLF'),
  array('iso' => 'EH','name' => 'WESTERN SAHARA','nicename' => 'Western Sahara','iso3' => 'ESH'),
  array('iso' => 'YE','name' => 'YEMEN','nicename' => 'Yemen','iso3' => 'YEM'),
  array('iso' => 'ZM','name' => 'ZAMBIA','nicename' => 'Zambia','iso3' => 'ZMB'),
  array('iso' => 'ZW','name' => 'ZIMBABWE','nicename' => 'Zimbabwe','iso3' => 'ZWE')
);
